# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{isna}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kazuyoshi tlacaelel"]
  s.date = %q{2011-11-14}
  s.description = %q{Easily compiles transforms a string into ansi code}
  s.email = %q{kazu.dev@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "isna.gemspec",
     "lib/isna.rb",
     "lib/isna/backgrounds.rb",
     "lib/isna/behaviours.rb",
     "lib/isna/colors.rb",
     "lib/isna/format.rb",
     "lib/isna/string.rb",
     "lib/isna_string_extension.rb",
     "test/helper.rb",
     "test/test_isna.rb"
  ]
  s.homepage = %q{http://github.com/ktlacaelel/isna}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple ansi library}
  s.test_files = [
    "test/helper.rb",
     "test/test_isna.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

